humusha/apps/words/forms.py
from sqlalchemy import or_

from flask_babel import gettext, ngettext, lazy_gettext as _
from flask import session

from flask_wtf import Form
from wtforms.fields import TextField, SubmitField, SelectField, HiddenField, FieldList, IntegerField
from wtforms.validators import Required as BaseRequired, ValidationError

from .models import Word, Part, WordPart, Relation, WordRelation, Language,\
    Translation


class Required(BaseRequired):
    def __init__(self, message=None):
        if message is None:
            message = _(u'This field is required.')
        super(Required, self).__init__(message)
        

class UniqueWord(object):
    """This class checks if the word does not exists."""
    def __init__(self, message=None):
        if not message:
            message = _(u'This word has already been added.')
        self.message = message

    def __call__(self, form, field):
        if Word.query.filter_by(word=field.data).count():
            raise ValidationError(self.message)

class RelationPart(object):
    """This class checks if the specified part can be a word relation."""
    def __init__(self, message=None):
        if not message:
            message = _(
                u'This part of speech can not be a relation.')
        self.message = message

    def __call__(self, form, field):
        try:
            part_id = int(field.data)
        except TypeError:
            part_id = None
            
        if not Relation.query.filter_by(part_id=part_id).count():
            raise ValidationError(self.message)


class TranslationLanguage(object):
    def __init__(self, message=None):
        if not message:
            message = _(
                u'This language has been added to this word part of speech.')
        self.message = message

    def __call__(self, form, field):
        try:
            part_id = int(form.part_id.data)
        except ValueError:
            part_id = None
        try:
            word_id = int(form.word_id.data)
        except ValueError:
            word_id = None
        if Translation.query.filter_by(part_id=part_id)\
                .filter_by(word_id=word_id).filter_by(language_id=int(field.data)).count():
            raise ValidationError(self.message)
    


class RelationLimit(object):
    """This class checks if added word relations have not reached the limit."""
    def __init__(self, message=None):
        if not message:
            message = _(
                u'The maximum word relations have been reached for this '\
                    'word and part of speech.')
        self.message = message

    def __call__(self, form, field):
        try:
            part_id = int(form.part.data)
        except TypeError:
            part_id = None
            
        relation = Relation.query.filter_by(part_id=part_id).first()
        if relation is None:
            raise ValidationError(self.message)

        word_count = WordRelation.query.filter(or_(
            WordRelation.word_id_1==form.word_id_,
            WordRelation.word_id_2==form.word_id_)).\
            filter(WordRelation.relation_id==relation.id).count()
        
        if word_count >= relation.limit and relation.limit:
            raise ValidationError(self.message)


class DynamicSelectField(SelectField):
    def __call__(self, parent_id=None, language_id=None, **kwargs):
        self.generate_choices(parent_id, language_id)

        return super(DynamicSelectField, self).__call__(**kwargs);

    def generate_choices(self, parent_id=None, language_id=None):
        parts = Part.query.filter_by(parent_id=parent_id)
        if language_id is not None:
            parts = parts.filter_by(language_id=language_id)
        if parent_id is None:
            parts = parts.filter(Part.name!='other')
        choices = [(p.id, _(p.label)) for p in parts]

        self.choices = choices
        
    

class SpeechTypeUnique(object):
    """This class checks if the word has been not been assigned to selected 
    type of speech.
    
    """
    def __init__(self, message=None):
        if not message:
            message = _(
                u'The selected type of speech is already associated with this word.'
            )
        self.message = message

    def __call__(self, form, field):
        if WordPart.query.filter_by(part_id=field.data,
                                    word_id=form.word_id_).count():
            raise ValidationError(self.message)


class WordForm(Form):
    word = TextField(_(_(u'Word')), validators=[
            Required(), UniqueWord()])
    language_id = HiddenField(_(u'Language'))
    submit = SubmitField(_(_(u'Add')))


class WordRelationForm(Form):
    word = FieldList(TextField(_(u'Word'), validators=[
                Required(), RelationLimit()]))
    word_relation = FieldList(HiddenField(_(u'Relation'), validators=[]))
    part = HiddenField(u'Part', validators=[RelationPart()])
    definition_id = HiddenField(_(u'Definition ID'), validators=[])
    translation_id = HiddenField(_(u'Translation ID'), validators=[])

    submit = SubmitField(_(u'Add'))
    
    @property
    def word_id(self):
        return self.word_id_

    @word_id.setter
    def word_id(self, value):
        self.word_id_ = value


class DefinitionForm(Form):
    definition = TextField(_(u'Definition'), validators=[])
    
    part = HiddenField(_(u'Part'), validators=[])
    definition_id = HiddenField(_(u'Definition ID'), validators=[])
    translation_id = HiddenField(_(u'Translation ID'), validators=[])

    submit = SubmitField(_(u'Define'))

class UsageForm(Form):
    sentence = FieldList(TextField(_(u'Usage examples'), []), min_entries=0)
    # sentence = FieldList(TextField(u'Usage examples', validators=[]))
    sentence_id = FieldList(HiddenField(_(u'Usage ID'), validators=[]))
    submit = SubmitField(_(u'Add'))


class SearchForm(Form):
    word = TextField(_(u'Word'), validators=[Required()])
    submit = SubmitField(_(u'Search'))


class TranslationForm(Form):
    language_id = SelectField(_(u'Language'), coerce=int, choices=[],
                              validators=[TranslationLanguage()])
    word_id = HiddenField(_(u'Word'))
    part_id = HiddenField(u'Part')
    submit = SubmitField(_(u'Add'))
    
    def language_choices(self):
        self.language_id.choices = [(l.id, l.label) for l in Language.query.all()]

class SpeechPartForm(Form):
    part = DynamicSelectField(_(u'Part of speech'), choices=[], coerce=int, validators=[
            SpeechTypeUnique()])

    parent_id = HiddenField(_(u'Parent type'))
    language_id = HiddenField(_(u'Language'))
    
    submit = SubmitField(_(u'Add'))

    @property
    def word_id(self):
        return self.word_id_
    
    @word_id.setter
    def word_id(self, value):
        self.word_id_ = value

    def validate(self):
        try:
            parent_id = int(self.parent_id.data)
            if not parent_id:
                parent_id = None
        except ValueError:
            parent_id = None
        try:
            language_id = int(self.language_id.data)
            if not language_id:
                language_id = None
        except ValueError:
            language_id = None

        parts = Part.query.filter_by(parent_id=parent_id)
        if language_id is None:
            parts = parts.filter_by(language_id=language_id)
        choices = [(p.id, p.label) for p in parts]
        self.part.choices = choices

        return super(SpeechPartForm, self).validate();

humusha/apps/words/views.py
from flask import render_template, flash, request, redirect, url_for, abort,\
    session, Blueprint
from werkzeug.datastructures import MultiDict
from flask_babel import gettext, ngettext, lazy_gettext as _

from humusha.utils.pagination import Pagination
from humusha import db

from .forms import WordForm, SearchForm, SpeechPartForm, DefinitionForm, \
    UsageForm, WordRelationForm, TranslationForm
from .models import Word, WordPart, Definition, Usage, Part, Relation,\
    WordRelation, Translation, Language, Change


words = Blueprint('words', __name__)

PER_PAGE = 80

@words.route('/')
@words.route('/<language_code>/', methods=['GET', 'POST'])
def index(language_code=None):
    page = request.args.get('page', 1)
    try:
        page = int(page)
        if page < 1:
            page = 1
    except ValueError:
        page = 1
    
    words = Word.query.order_by('word.id DESC')\
        .slice((page - 1)*PER_PAGE, page*PER_PAGE).all()

    words_count = Word.query.order_by('word.id DESC').count()
    pagination = Pagination(page, PER_PAGE, words_count)

    ctx = {
        'words': words,
        'pagination': pagination,
    }
    return render_template('words/words.html', **ctx)

@words.route('/browse/<starts_with>/')
@words.route('/browse/<starts_with>/<language_code>/', methods=['GET', 'POST'])
def browse(starts_with, language_code=None):
    page = request.args.get('page', 1)
    try:
        page = int(page)
        if page < 1:
            page = 1
    except ValueError:
        page = 1

    words = Word.query.filter(Word.word.startswith(starts_with))\
        .order_by('word.id DESC').slice((page - 1)*PER_PAGE, page*PER_PAGE).all()
    words_count = Word.query.filter(Word.word.startswith(starts_with)).count()
    pagination = Pagination(page, PER_PAGE, words_count)
        
    ctx = {
        'words': words,
        'pagination': pagination,
    }
    return render_template('words/browse.html', **ctx)


@words.route('/<word_data>', methods=['GET', 'POST'])
@words.route('/<language_code>/<word_data>', methods=['GET', 'POST'])
def view(word_data, language_code=None):
    word = Word.get_word(word_data, language_code)
    if word is None:
        abort(404)
    speech_parts = WordPart.query.join('part').filter(WordPart.word_id==word.id)\
        .filter(Part.parent_id==None)
    
    words = Word.query.filter(Word.word.like('%{0}%'.format(word_data)))
    thesaurus_parts = Part.thesaurus_parts(word.language_id)
    translation_part = Part.translation_part(word.language_id)

    ctx = {
        'word': word,
        'speech_parts': speech_parts,
        'words': words,
        'thesaurus_parts': thesaurus_parts,
        'translation_part': translation_part,
    }
    return render_template('words/view_word.html', **ctx)


@words.route('/<language_code>/edit/<word_data>/', methods=['GET', 'POST'])
@words.route('/<language_code>/edit/<word_data>/p<int:part_data>', methods=['GET', 'POST'])
@words.route('/<language_code>/edit/<word_data>/d<int:definition_data>', methods=['GET', 'POST'])
def edit(word_data, definition_data=None, part_data=None, language_code=None):
    word = Word.get_word(word_data, language_code)
    if word is None:
        abort(404)

    speech_parts = WordPart.query.join('part').filter(WordPart.word_id==word.id)\
        .filter(Part.parent_id == None)
    thesaurus_parts = Part.thesaurus_parts(word.language_id)

    translation_part = Part.translation_part(word.language_id)

    speech_part_form = SpeechPartForm()

    speech_part_form.word_id = word.id
    # speech_part_form.set_word(word.id)

    definition_form = DefinitionForm()
    usage_form = UsageForm()
    word_relation_form = WordRelationForm()
    translation_form = TranslationForm()
    translation_form.language_choices()

    words = Word.query.filter(Word.word.like('%{0}%'.format(word_data)))

    if speech_part_form.validate_on_submit():
        word_part = WordPart(word.id, speech_part_form.part.data)
        db.session.add(word_part)
        db.session.commit()
        flash(gettext(u'The word has been associated with the part of speech.'), 'success')
        
    ctx = {
        'word': word,
        'speech_parts': speech_parts,
        'usage_form': usage_form,
        'thesaurus_parts': thesaurus_parts,
        'translation_part': translation_part,
        'words': words,
        'word_relation_form': word_relation_form,
        'definition_form': definition_form,
        'speech_part_form': speech_part_form,
        'translation_form': translation_form,
    }
    return render_template('words/edit_word.html', **ctx)


@words.route('/<language_code>/add_definition/<word_data>', methods=['POST'])
def add_definition(word_data, language_code=None):
    word = Word.get_word(word_data, language_code)
    if word is None:
        abort(404)
    definition_form = DefinitionForm(csrf_enabled=False)
    usage_form = UsageForm(csrf_enabled=False)

    if definition_form.validate_on_submit() and usage_form.validate_on_submit():
        definition_data = definition_form.definition.data
        definition_id_data = definition_form.definition_id.data
        part_id_data = definition_form.part.data
        sentences_data = usage_form.sentence.data
        sentences_id_data = usage_form.sentence_id.data
        try:
            translation_id_data = int(definition_form.translation_id.data)
        except ValueError:
            translation_id_data = None

        part = Part.query.filter_by(id=part_id_data).first()
    
        try:
            definition_id_data = int(definition_id_data)
            definition = Definition.query.filter_by(id=definition_id_data).first()
        except ValueError:
            definition = None

        if definition_data and word is not None:
            if definition is not None:
                definition.definition=definition_data
            else:
                definition = Definition(
                    definition=definition_data,
                    word_id=word.id,
                    part_id=part_id_data)
                definition.translation_id = translation_id_data
            db.session.add(definition)
            db.session.commit()
            for sentence_index, sentence_data in enumerate(sentences_data):
                
                if not sentence_index > len(sentences_id_data)-1:
                    usage = Usage.query.filter_by(
                        id=sentences_id_data[sentence_index]).first()
                else:
                    usage = None
                if usage is not None:
                    if not sentence_data:
                        db.session.delete(usage)
                    else:
                        usage.sentence=sentence_data
                        db.session.add(usage)
                else:
                    if not sentence_data:
                        continue
                    usage = Usage(sentence=sentence_data,
                                  definition_id=definition.id)
                    db.session.add(usage)
            db.session.commit()
            flash(gettext(u'Definition added.'), 'success')
        else:
            flash(gettext(u'Definition not added.'), 'error')
    else:
        flash(gettext(u'Definition not added.'), 'error')

    return redirect(url_for('words.edit', language_code=language_code, word_data=word_data))


@words.route('/<language_code>/edit/relation/<word_data>', methods=['POST'])
def relation(word_data, language_code=None, form_class = WordRelationForm):
    word_relation_form = form_class()
    
    word_1 = Word.get_word(word_data, language_code)
    if word_1 is None:
        return redirect(url_for('words.edit', language_code=language_code, word_data=word_data))

    word_relation_form.word_id = word_1.id

    validates = word_relation_form.validate_on_submit()
    
    word_relation = None
    for word_index, word_data_2 in enumerate(word_relation_form.word.data):
        word_relation = None
        try:
            part_data = int(word_relation_form.part.data)
        except ValueError:
            part_data = None
        relation = Relation.query.filter(Relation.part_id==part_data).first()
        try:
            translation_id_data = int(word_relation_form.translation_id.data)
            translation = Translation.query\
                .filter(Translation.id==translation_id_data).first()
            language_id = translation.language_id
        except ValueError:
            translation_id_data = None
            translation = None
            language_id = word_1.language_id
        try:
            definition_id_data = int(word_relation_form.definition_id.data)
        except ValueError:
            definition_id_data = None

        if word_index < len(word_relation_form.word_relation.data): # Update
            word_relation_data = int(word_relation_form.word_relation.data[word_index])
        elif not validates: # Relation limit reached
            continue
        else: # New word relation
            word_relation_data = None

        word_2 = Word.query.filter(Word.word==word_data_2)\
            .filter(Word.language_id==language_id).first()

        if word_2 is None:
            word_2 = Word(word=word_data_2, language_id=language_id)
            db.session.add(word_2)
            db.session.commit()
            flash(gettext(u'Relation word was added.'), 'success')
        
        if word_relation_data is not None:
             word_relation = WordRelation.query\
                .filter(WordRelation.translation_id==translation_id_data)\
                .filter(WordRelation.relation_id==relation.id)\
                .filter(WordRelation.id==word_relation_data).first()
             if word_relation is None:
                 continue
        else:
            word_relation = WordRelation.query\
                .filter(WordRelation.translation_id==translation_id_data)\
                .filter(WordRelation.word_id_1==word_1.id)\

humusha/templates/words/_word_heading.html
{# word heading for the view and edit pages (defaults to read mode) #}
{% macro word_heading_render(view_mode="read") %}
  <div class="row">

    <div class="large-4 columns">
      <h1><a href="{{ url_for("words.view", word_data=word.word) }}">{{ word.word }}</a></h1>
    </div>
    <div class="large-2 columns">
      <br />
      <br />
      [{{ word.language.label }}]
    </div>
    <div class="large-offset-9 caps">
      <div class="text-right">
        <br />
        <br />
        {% if not view_mode == "history" %}
          <a href="{{ url_for("words.history", language_code=word.language.code, word_data=word.word) }}">{{ gettext('History') }}</a> &nbsp;
        {% endif %}
        {% if not view_mode == "read" %}
          <a href="{{ url_for("words.view", language_code=word.language.code, word_data=word.word) }}">{{ gettext('Read-only') }}</a>
        {% else %}
          <a href="{{ url_for("words.edit", language_code=word.language.code, word_data=word.word) }}">{{ gettext('Edit') }}</a>
        {% endif %}
      </div>
    </div>

  </div>
{% endmacro %}

humusha/templates/words/_words_display.html
<div class="row">
  {% for word in words %}
    <div class="large-3 columns">
      <a href="{{ url_for('words.view', language_code=word.language.code, word_data=word.word) }}">{{ word.word }}</a>
    </div>
  {% endfor %}
</div>

humusha/templates/words/add_words.html
{% extends "layout.html" %}
{% block title %}Add{% endblock %}
{% block content %}

  <div class="row">
    <div class="large-12 columns">
      <h1>{{ gettext('Add') }}</h1>
      <hr />
    </div>
  </div>
  
  <div class="row">
    <div class="large-12 columns">

      <form action="{{ url_for("words.add") }}" method="POST">
        {{ form.csrf_token }}
        {% if form.word.errors %}
          <div class="notice">
            {% for error in form.word.errors %}<div>{{ error|e }}</div>{% endfor %}
          </div>
        {% endif %}

        <div class="row collapse"> 
          <div class="large-11 columns"> 
            {{ form.word }}
          </div>

          <div class="large-1 columns"> 
            {{ form.submit(class="button postfix") }}
          </div>
        </div>
      </form>
      
      <hr />
    </div>
  </div>

  
  {% include "words/_words_display.html" %}
  
  <div class="row">
    <div class="large-12 columns">
      {{ render_pagination(pagination) }}
    </div>
  </div>

{% endblock %}

humusha/templates/words/browse.html
{% extends "layout.html" %}
{% block title %}Browse Words{% endblock %}
{% block content %}

  <div class="row">
    <div class="large-12 columns">
      <h1>{{ gettext('Words') }}</h1>
    </div>
  </div>

  {% include "words/_words_display.html" %}

  <div class="row">
    <div class="text-right">
      {{ render_pagination(pagination) }}
    </div>
  </div>

{% endblock %}

humusha/templates/words/edit_word.html
{% extends "layout.html" %}
{% block title %}Words{% endblock %}
{% block content %}

  {# word heading and main actions (edit/history/discuss?) #}
  {% from "words/_word_heading.html" import word_heading_render with context %}
  {{ word_heading_render(view_mode="edit") }}


  <hr />

  {# START ADD MASTER PART OF SPEECH #}
  {% include "words/edit/_master_part.html" %}
  {# END ADD MASTER PART OF SPEECH #}

  <hr />


  {% for word_part in speech_parts %}

    {# START MAIN PART #}
    {% include "words/edit/_sub_part_add.html" %}
    {# END MAIN PART #}
    
    
    {# START CHILDREN PARTS #}
    {% include "words/edit/_part_subpart.html" %}
    {# END CHILDREN PARTS #}


    {# START CHILDREN PARTS #}
    {% include "words/edit/_definitions.html" %}
    {# END CHILDREN PARTS #}
    
  {% endfor %}

  {# START THESAURUS #}  
  <div id="thesaurus">
    {% include "words/edit/_thesaurus.html" %}
  </div>
  {# END THESAURUS #}
  


  {# START TRANSLATIONS #}
  <div id="translations">
    {% include "words/edit/_translations.html" %}
  </div>
  {# END TRANSLATIONS #}
      
{% endblock %}

humusha/templates/words/history.html
{% extends "layout.html" %}
{% block title %}History{% endblock %}
{% block content %}

  {% from "words/_word_heading.html" import word_heading_render with context %}
  {{ word_heading_render(view_mode="history") }}

  <h3>{{ gettext('History') }}</h3>
  
  {% for revision in revisions %}
    <div class="row-fluid">
      <div class="span4">
        {% set prev_revision = revision.prev_revision %}
        {% if prev_revision %}
          {{ prev_revision.history_object() }}
        {% endif %}
        &nbsp;
      </div>
      <div class="span5">
        {{ revision.history_object() }}
        &nbsp;
      </div>
      <div class="span3">
        <div class="row-fluid">
          <div class="span3">
            {{ revision.action }}
          </div>
          <div class="span8">
            {{ revision.created|datetimeformat }}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

{% endblock %}

humusha/templates/words/search_words.html
{% extends "layout.html" %}
{% block title %}Search{% endblock %}
{% block content %}

  <div class="row">
    <div class="large-12 columns">
      <h1>{{ gettext('Search') }}</h1>
      <hr />
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <form action="{{ url_for("words.search") }}" class="form-search" method="POST">
        {% if form.word.errors %}
          <div class="notice">
            {% for error in form.word.errors %}<div>{{ error|e }}</div>{% endfor %}
          </div>
        {% endif %}
        {{ search_form.csrf_token }}{# {{ form.csrf }} #}
        <div class="row collapse"> 
          <div class="large-11 columns"> 
            {{ form.word(class="span7 input-medium search-query") }}
          </div>
          <div class="large-1 columns"> 
            {{ form.submit(class="button postfix") }}
          </div>
        </div>
      </form>
      <hr />
    </div>
  </div>

  
  {% include "words/_words_display.html" %}
  
  <div class="row">
    <div class="large-12 columns">
      {{ render_pagination(pagination) }}
    </div>
  </div>

  
{% endblock %}

humusha/templates/words/statistics.html
{% extends "layout.html" %}
{% block title %}{{ gettext('Statistics') }}{% endblock %}
{% block content %}

  <h1>{{ gettext('Statistics') }}</h1>
  
  <hr />

  
{% endblock %}

humusha/templates/words/view_word.html
{% extends "layout.html" %}
{% block title %}Words{% endblock %}
{% block content %}

  {# word heading and main actions (edit/history/discuss?) #}
  {% from "words/_word_heading.html" import word_heading_render with context %}
  <div class="row">
    <div class="large-12 columns">

      {{ word_heading_render() }}

      <hr />
    </div>
  </div>


  {% for word_part in speech_parts %}
    <div class="row">
      <div class="large-12 columns">
        <h4 class="no-margin">{{ word_part.part.label }}</h4>
      </div>
    </div>
    
    <div class="row">
      <div class="large-12 columns">

        {% for part_type in word_part.part_types %}
          <div class="row">
            <div class="large-12 columns">
              <div class="large-2 columns">
                <h5>{{ part_type.part.label }}</h5>
              </div>
              {% if part_type.part.relation.part_id %}
                <div class="large-2 columns">
                  <em>{{ ngettext("of word", "of words", part_type.part.relation.limit) }}</em>
                </div>
                <div class="large-8 columns">
                  {% for word_relation in word.relations(part_type.part.id) %}
                    {% if not word_relation.word_id_1 == word.id %}
                      {{ word_relation.word_1.word }}
                    {% else %}
                      {{ word_relation.word_2.word }}
                    {% endif %}
                  {% endfor %}
                </div>
              {% endif %}
            </div>
          </div>
        {% endfor %}
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">

        <ul>
	  {% for definition in word_part.word.definitions(word_part.part_id) %}
	    <li>
	      {{ definition.definition }}
	    </li>
	    <ol>
	      {% for usage_example in definition.usage_examples %}
	        <li>
		  <em>{{ usage_example.sentence }}</em>
	        </li>
	      {% endfor %}
	    </ol>
	  {% endfor %}
        </ul>
      </div>
    </div>

{% endfor %}


<div class="row">
  <div class="large-12 columns">

    {% for thesaurus_part in thesaurus_parts %}
      {% if not thesaurus_part.dependants_exist() %}{% continue %}{% endif %}
      <div class="row">
        <div class="large-12 columns">
          <h4 class="no-margin">{{ thesaurus_part.label }}</h4>
        </div>
      </div>
      <div class="row">
        <div class="large-12 columns">

          {% for definition in word.definitions(thesaurus_part.id) %}
            <ul>
              {% if not request.view_args.definition_data == definition.id %}
	        <li>
                  {{ definition.definition }}
                </li>
              {% endif %}
              <div class="row">
                <div class="large-12 columns">
                  {% for word_relation in word.relations(thesaurus_part.id, definition.id) %}
                    <div class="large-1 columns">
                      {% if not word_relation.word_id_1 == word.id %}
                        {{ word_relation.word_1.word }}
                      {% else %}
                        {{ word_relation.word_2.word }}
                      {% endif %}
                    </div>
                  {% endfor %}
                </div>
              </div>
            </ul>
          {% endfor %}
        </div>
      </div>
      <div class="row">
        <div class="large-12 columns">

          {# global (not belonging to a definition) part words #}
          {% for word_relation in word.relations(thesaurus_part.id) %}
            <div class="large-1 columns">
              {% if not word_relation.word_id_1 == word.id %}
                {{ word_relation.word_1.word }}
              {% else %}
                {{ word_relation.word_2.word }}
              {% endif %}
            </div>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    {# START TRANSLATIONS #}

    <div class="row">
      <div class="large-12 columns">
        {% if translation_part.dependants_exist() %}
          <h4 class="no-margin">{{ translation_part.label }}</h4>
        {% endif %}
      </div>
    </div>
    
    <div class="row">
      <div class="large-12 columns">
        {% for translation in translation_part.translation_languages(word.id) %}
          {% if not translation_part.dependants_exist() %}{% continue %}{% endif %}
          <h5>{{ translation.language.label }}</h5>
          
          <div class="row">
            <div class="large-12 columns">
              {% for definition in word.definitions(translation_part.id, translation_id=translation.id) %}
                <ul>
                  {% if not request.view_args.definition_data == definition.id %}
	            <li>
                      {{ definition.definition }}
                    </li>
                  {% endif %}
                  <div class="row">
                    <div class="large-12 columns">
                      {% for word_relation in word.relations(translation_part.id, definition.id, translation_id=translation.id) %}
                        <div class="large-1 columns">
                          {% if not word_relation.word_id_1 == word.id %}
                            {{ word_relation.word_1.word }}
                          {% else %}
                            {{ word_relation.word_2.word }}
                          {% endif %}
                        </div>
                      {% endfor %}
                    </div>
                  </div>
                </ul>
              {% endfor %}
            </div>
          </div>
          <div class="row">
            <div class="large-12 columns">
              {# global (not belonging to a definition) part words #}
              {% for word_relation in word.relations(translation_part.id, translation_id=translation.id) %}
                <div class="large-1 columns">
                  {% if not word_relation.word_id_1 == word.id %}
                    {{ word_relation.word_1.word }}
                  {% else %}
                    {{ word_relation.word_2.word }}
                  {% endif %}
                </div>
              {% endfor %}
            </div>
          </div>
          
        {% endfor %}
      </div>
    </div>
    
  </div>
  {# END TRANSLATIONS #}
</div>

<hr />

{% include "words/_words_display.html" %}

{% endblock %}

humusha/templates/words/words.html
{% extends "layout.html" %}
{% block title %}Words{% endblock %}
{% block content %}

  <div class="row">
    <div class="large-12 columns">
      <h1>{{ gettext('Words') }}</h1>
      <hr />
    </div>
  </div>

  {% include "words/_words_display.html" %}
  
  <div class="row">
    <div class="large-12 columns">
      <div class="text-right">
        {{ render_pagination(pagination) }}
      </div>
    </div>
  </div>

{% endblock %}