humusha/apps/words/views.py
from flask import render_template, flash, request, redirect, url_for, abort,\
    session, Blueprint
from werkzeug.datastructures import MultiDict
from flask_babel import gettext, ngettext, lazy_gettext as _

from humusha.utils.pagination import Pagination
from humusha import db

from .forms import WordForm, SearchForm, SpeechPartForm, DefinitionForm, \
    UsageForm, WordRelationForm, TranslationForm
from .models import Word, WordPart, Definition, Usage, Part, Relation,\
    WordRelation, Translation, Language, Change


words = Blueprint('words', __name__)

PER_PAGE = 80

@words.route('/')
@words.route('/<language_code>/', methods=['GET', 'POST'])
def index(language_code=None):
    page = request.args.get('page', 1)
    try:
        page = int(page)
        if page < 1:
            page = 1
    except ValueError:
        page = 1
    
    words = Word.query.order_by('word.id DESC')\
        .slice((page - 1)*PER_PAGE, page*PER_PAGE).all()

    words_count = Word.query.order_by('word.id DESC').count()
    pagination = Pagination(page, PER_PAGE, words_count)

    ctx = {
        'words': words,
        'pagination': pagination,
    }
    return render_template('words/words.html', **ctx)

@words.route('/browse/<starts_with>/')
@words.route('/browse/<starts_with>/<language_code>/', methods=['GET', 'POST'])
def browse(starts_with, language_code=None):
    page = request.args.get('page', 1)
    try:
        page = int(page)
        if page < 1:
            page = 1
    except ValueError:
        page = 1

    words = Word.query.filter(Word.word.startswith(starts_with))\
        .order_by('word.id DESC').slice((page - 1)*PER_PAGE, page*PER_PAGE).all()
    words_count = Word.query.filter(Word.word.startswith(starts_with)).count()
    pagination = Pagination(page, PER_PAGE, words_count)
        
    ctx = {
        'words': words,
        'pagination': pagination,
    }
    return render_template('words/browse.html', **ctx)


@words.route('/<word_data>', methods=['GET', 'POST'])
@words.route('/<language_code>/<word_data>', methods=['GET', 'POST'])
def view(word_data, language_code=None):
    word = Word.get_word(word_data, language_code)
    if word is None:
        abort(404)
    speech_parts = WordPart.query.join('part').filter(WordPart.word_id==word.id)\
        .filter(Part.parent_id==None)
    
    words = Word.query.filter(Word.word.like('%{0}%'.format(word_data)))
    thesaurus_parts = Part.thesaurus_parts(word.language_id)
    translation_part = Part.translation_part(word.language_id)

    ctx = {
        'word': word,
        'speech_parts': speech_parts,
        'words': words,
        'thesaurus_parts': thesaurus_parts,
        'translation_part': translation_part,
    }
    return render_template('words/view_word.html', **ctx)


@words.route('/<language_code>/edit/<word_data>/', methods=['GET', 'POST'])
@words.route('/<language_code>/edit/<word_data>/p<int:part_data>', methods=['GET', 'POST'])
@words.route('/<language_code>/edit/<word_data>/d<int:definition_data>', methods=['GET', 'POST'])
def edit(word_data, definition_data=None, part_data=None, language_code=None):
    word = Word.get_word(word_data, language_code)
    if word is None:
        abort(404)

    speech_parts = WordPart.query.join('part').filter(WordPart.word_id==word.id)\
        .filter(Part.parent_id == None)
    thesaurus_parts = Part.thesaurus_parts(word.language_id)

    translation_part = Part.translation_part(word.language_id)

    speech_part_form = SpeechPartForm()

    speech_part_form.word_id = word.id
    # speech_part_form.set_word(word.id)

    definition_form = DefinitionForm()
    usage_form = UsageForm()
    word_relation_form = WordRelationForm()
    translation_form = TranslationForm()
    translation_form.language_choices()

    words = Word.query.filter(Word.word.like('%{0}%'.format(word_data)))

    if speech_part_form.validate_on_submit():
        word_part = WordPart(word.id, speech_part_form.part.data)
        db.session.add(word_part)
        db.session.commit()
        flash(gettext(u'The word has been associated with the part of speech.'), 'success')
        
    ctx = {
        'word': word,
        'speech_parts': speech_parts,
        'usage_form': usage_form,
        'thesaurus_parts': thesaurus_parts,
        'translation_part': translation_part,
        'words': words,
        'word_relation_form': word_relation_form,
        'definition_form': definition_form,
        'speech_part_form': speech_part_form,
        'translation_form': translation_form,
    }
    return render_template('words/edit_word.html', **ctx)


@words.route('/<language_code>/add_definition/<word_data>', methods=['POST'])
def add_definition(word_data, language_code=None):
    word = Word.get_word(word_data, language_code)
    if word is None:
        abort(404)
    definition_form = DefinitionForm(csrf_enabled=False)
    usage_form = UsageForm(csrf_enabled=False)

    if definition_form.validate_on_submit() and usage_form.validate_on_submit():
        definition_data = definition_form.definition.data
        definition_id_data = definition_form.definition_id.data
        part_id_data = definition_form.part.data
        sentences_data = usage_form.sentence.data
        sentences_id_data = usage_form.sentence_id.data
        try:
            translation_id_data = int(definition_form.translation_id.data)
        except ValueError:
            translation_id_data = None

        part = Part.query.filter_by(id=part_id_data).first()
    
        try:
            definition_id_data = int(definition_id_data)
            definition = Definition.query.filter_by(id=definition_id_data).first()
        except ValueError:
            definition = None

        if definition_data and word is not None:
            if definition is not None:
                definition.definition=definition_data
            else:
                definition = Definition(
                    definition=definition_data,
                    word_id=word.id,
                    part_id=part_id_data)
                definition.translation_id = translation_id_data
            db.session.add(definition)
            db.session.commit()
            for sentence_index, sentence_data in enumerate(sentences_data):
                
                if not sentence_index > len(sentences_id_data)-1:
                    usage = Usage.query.filter_by(
                        id=sentences_id_data[sentence_index]).first()
                else:
                    usage = None
                if usage is not None:
                    if not sentence_data:
                        db.session.delete(usage)
                    else:
                        usage.sentence=sentence_data
                        db.session.add(usage)
                else:
                    if not sentence_data:
                        continue
                    usage = Usage(sentence=sentence_data,
                                  definition_id=definition.id)
                    db.session.add(usage)
            db.session.commit()
            flash(gettext(u'Definition added.'), 'success')
        else:
            flash(gettext(u'Definition not added.'), 'error')
    else:
        flash(gettext(u'Definition not added.'), 'error')

    return redirect(url_for('words.edit', language_code=language_code, word_data=word_data))


@words.route('/<language_code>/edit/relation/<word_data>', methods=['POST'])
def relation(word_data, language_code=None, form_class = WordRelationForm):
    word_relation_form = form_class()
    
    word_1 = Word.get_word(word_data, language_code)
    if word_1 is None:
        return redirect(url_for('words.edit', language_code=language_code, word_data=word_data))

    word_relation_form.word_id = word_1.id

    validates = word_relation_form.validate_on_submit()
    
    word_relation = None
    for word_index, word_data_2 in enumerate(word_relation_form.word.data):
        word_relation = None
        try:
            part_data = int(word_relation_form.part.data)
        except ValueError:
            part_data = None
        relation = Relation.query.filter(Relation.part_id==part_data).first()
        try:
            translation_id_data = int(word_relation_form.translation_id.data)
            translation = Translation.query\
                .filter(Translation.id==translation_id_data).first()
            language_id = translation.language_id
        except ValueError:
            translation_id_data = None
            translation = None
            language_id = word_1.language_id
        try:
            definition_id_data = int(word_relation_form.definition_id.data)
        except ValueError:
            definition_id_data = None

        if word_index < len(word_relation_form.word_relation.data): # Update
            word_relation_data = int(word_relation_form.word_relation.data[word_index])
        elif not validates: # Relation limit reached
            continue
        else: # New word relation
            word_relation_data = None

        word_2 = Word.query.filter(Word.word==word_data_2)\
            .filter(Word.language_id==language_id).first()

        if word_2 is None:
            word_2 = Word(word=word_data_2, language_id=language_id)
            db.session.add(word_2)
            db.session.commit()
            flash(gettext(u'Relation word was added.'), 'success')
        
        if word_relation_data is not None:
             word_relation = WordRelation.query\
                .filter(WordRelation.translation_id==translation_id_data)\
                .filter(WordRelation.relation_id==relation.id)\
                .filter(WordRelation.id==word_relation_data).first()
             if word_relation is None:
                 continue
        else:
            word_relation = WordRelation.query\
                .filter(WordRelation.translation_id==translation_id_data)\
                .filter(WordRelation.word_id_1==word_1.id)\

humusha/templates/_common.html
{# language switching form (type "app_language" for global site language
and "language" for content contribution language) #}
{% macro render_language_form(language_type) %}
  {% set language_data = session[language_type]|language_data %}
  <div class="btn-group">
    <button class="btn">{{ language_data.label }}</button>
    <button class="btn dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      {% for language in languages %}
        {% if language.id == session[language_type] %}
          {% continue %}
        {% endif %}
        <li><a href="{{ url_for('switch_language', language_type=language_type, language_code=language.code) }}">{{ language.label }}</a></li>
      {% endfor %}
    </ul>
   </div>
{% endmacro %}

humusha/templates/_featured.html
{% for language_featured in featured_words %}
  {% if not featured_words[language_featured]|count %}
    {% continue %}
  {% endif %}
  <div class="item{% if loop.first %} active{% endif %}">

    {% for word in featured_words[language_featured] %}
      <div class="row-fluid">
        <strong>{{ word.word }}</strong>
      </div>
      
      <div class="row-fluid">
        <div>
          <ol>
            {% for definition in word.definitions(none, none, 3) %}
              <li>
                {{ definition.definition }}
                <ul>
                  {% for usage in definition.usage_examples %}
                    <li>{{ usage.sentence }}</li>
                  {% endfor %}
                </ul>
              </li>
          {% endfor %}
          </ol>
        </div>
      </div>
    {% endfor %}

  </div>
{% endfor %}

humusha/templates/_global_search.html
<div>
  <form action="{{ url_for("words.search") }}" class="form-search" method="POST">
    {{ search_form.csrf_token }}
    {{ search_form.word(class="input-medium search-query", placeholder="Search") }}
    {{ search_form.submit(class="btn") }}
  </form>
</div>

humusha/templates/_pagination.html
{% macro render_pagination(pagination) %}
  <hr />
  <nav>
    <ul class="pagination">
      {% if pagination.has_prev %}
        <li class="arrow"><a href="{{ url_for_other_page(pagination.page - 1) }}">&laquo;</a></li>
      {% else %}
        <li class="arrow unavailable"><a>&laquo;</a></li>
      {% endif %}
      {% for page in pagination.iter_pages() %}
        {% if page %}
          {% if page != pagination.page %}
            <li><a href="{{ url_for_other_page(page) }}">{{ page }}</a></li>
          {% else %}
            <li class="current"><a>{{ page }}</a></li>
          {% endif %}
        {% endif %}
      {% endfor %}
      {% if pagination.has_next %}
        <li class="arrow"><a href="{{ url_for_other_page(pagination.page + 1) }}">&raquo;</a></li>
      {% else %}
        <li class="arrow unavailable"><a>&raquo;</a></li>
      {% endif %}
    </ul>
  </nav>
{% endmacro %}

humusha/templates/index.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block content %}
  
  <div class="row">
    <div class="large-12 columns">
      <hr />
      <strong>Welcome!</strong> Use the search function below or read the help manual to get started<br />
      <br />
    </div>
  </div>

  {# START SEARCH FORM #}
  <div class="row">
    <form action="{{ url_for("words.search") }}" class="clearfix" method="POST"> 
      <div class="large-12 columns"> 
        <div class="row collapse"> 
          <div class="large-11 columns"> 
            {{ search_form.csrf_token }} 
            {{ form.word(placeholder="Search") }} 
          </div> 
          <div class="large-1 columns"> 
            {{ form.submit(class="button postfix") }} 
          </div> 
        </div> 
      </div> 
      <div class="large-12 columns text-center"> 
        (search, view, make corrections, expand and add new words)  
        <hr /> 
      </div> 
      <br /> 
    </form>  
    {# END SEARCH FORM #}
  </div> 

  <div class="row">
    {# START BROWSE #}

    
    <div class="large-1 columns">
      <strong>{{ gettext("Browse") }}:</strong>
    </div>
    
    <div class="large-11 columns">
      {% for ascii_letter in ascii_letters %}
        <a href="{{ url_for("words.browse", starts_with=ascii_letter) }}">{{ ascii_letter }}</a>
        <a href="{{ url_for("words.browse", starts_with=ascii_letter|upper) }}">{{ ascii_letter|upper }}</a>
      {% endfor %}
    </div>

    {# END BROWSE #}
  </div>
  
  <br />
  <br />

  <br />
  <br />

  <br />
  <br />

  <br />
  <br />




  {#
  <h1>Zabalaza Afrika</h1>
  <hr />
  <div class="container">
    <div class="container center">
      <strong>
        <!-- Thanks to en.Wiktionary for the nice wording :) -->
        A collaborative project to produce a translator, dictionaries,
        thesauruses and other important written works, for African
        languages.
      </strong>
    </div>
    <div class="container">
      <form action="{{ url_for("words.search") }}" method="POST">
        {{ search_form.csrf_token }}
        <div class="prepend-5 span-12 last">
          {{ form.word(class='span-12', placeholder="Search or add new words") }}
        </div>
        <div class="spa-2">
          {{ form.submit(style="display:inline-block;line-height:22px;") }}
        </div>
      </form>
    </div>
  </div>

  <div class="container">
    <h3>{{ gettext("Browse") }}</h3>

    <div class="container">
      <div class="large center">
        {% for ascii_letter in ascii_letters %}
          <a href="{{ url_for("words.browse", starts_with=ascii_letter) }}">{{ ascii_letter }}</a>
          <a href="{{ url_for("words.browse", starts_with=ascii_letter|upper) }}">{{ ascii_letter|upper }}</a>
        {% endfor %}
      </div>
    </div>

  </div>

  <div class="container">
    <h3>{{ gettext("Languages") }}</h3>
    <ul>
      <div class="container">
        {% for language in languages %}
          <div class="column">
            <li>
              <a class="" style="line-height:1.8em !important;" href="{{ url_for("words.index", language_code=language.code) }}">{{ language.label }}</a>
              &nbsp;&nbsp;&nbsp;
            </li>
          </div>
        {% endfor %}
      </div>
    </ul>
    
  </div>
  #}
  
{% endblock %}

humusha/templates/layout.html
<!DOCTYPE html>
<html>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/default.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/humusha.css') }}" />
  <head>
    <title>{% block title %}{% endblock %} - Humusha</title>
  </head>
  <body>
    {% from "_common.html" import render_language_form with context %}
    {% from "_pagination.html" import render_pagination with context %}

    
    {% macro with_errors(field) %}
      <div class="field">
        <label>{{ field.label }}</label>
        {% set css_class = kwargs.pop('class', '') %}
        {% if not css_class %}
	  {% set css_class = 'clearfix span-17 ' + css_class %}
	{% else %}
	  {% set css_class = 'clearfix ' + css_class %}
	{% endif %}
        {% if field.errors %}
	  
	  <div  class="clearfix">
            {{ field(class=css_class, **kwargs) }}
          </div>
          <div class="notice">{% for error in field.errors %}<div>{{ error|e }}</div>{% endfor %}</div>
	{% else %}
	  <div class="clearfix">
            {{ field(class=css_class, **kwargs) }}
          </div>
        {% endif %}
      </div>
    {% endmacro %}

    <div class="row">
      <div class="large-9 columns">
        <div id="home"><a href="{{ url_for("home") }}">Humusha</a></div>
        <br />
        <div>The free multi-language dictionary and thesaurus that anyone can edit</div>
      </div>
      
      <div class="large-3 columns">
        <br />
        <br />
        <br />
        <div class="row">
          <div class="large-4 columns">
            <a href="{{ url_for("words.index") }}">{{ gettext('Words') }}</a>
          </div>
          <div class="large-4 columns">
            <a href="{{ url_for("words.add") }}">{{ gettext('Add') }}</a>
          </div>
          <div class="large-4 columns"> 
            <a href="{{ url_for("words.search") }}">{{ gettext('Search') }}</a> 
          </div> 
          {# <div class="large-2 columns">  #}
          {#   {{ gettext('Statistics') }}{\# <a href="{{ url_for("words.statistics") }}">{{ gettext('Statistics') }}</a>  #\} #}
          {# </div>  #}
          {# <div class="large-2 columns">  #}
          {#   {{ gettext('Activity') }}  #}
          {# </div>  #}
          {# <div class="large-2 columns">  #}
          {#   {{ gettext('Translate') }}  #}
          {# </div>  #}
        </div>
      </div>
    </div>
    {# END HEADER #}

    
    {# START BODY #}
    
    {% block content %}{% endblock %}
        
    {# END BODY #}

    <div class="row">
      <div class="large-12 columns">
        <div class="row">
          {# START FOOTER #}

          <div class="large-12 columns">
            <br />
            <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">
              <img alt="Creative Commons License" style="border-width:0"
                   src="/static/img/cc-by-sa-88x31.png" /></a>
                   <br />
                   This <span xmlns:dct="http://purl.org/dc/terms/"
                   href="http://purl.org/dc/dcmitype/Text"
                   rel="dct:type">work</span> is licensed under a <a rel="license"
                   href="http://creativecommons.org/licenses/by-sa/3.0/">Creative
                   Commons Attribution-ShareAlike 3.0 Unported License</a>.
                   
                   {# END FOOTER #}
          </div>
        </div>
      </div>
    </div>


    <br />
    <br />
    <br />
    <br />
    {# <div class="container clear"> 
    <div class="container clear">
      <div id="home" class="span-8"><a href="{{ url_for("home") }}">Humusha</a></div>
      <div id="menu" class="span-11">
	<ul>
	  <li>
	    <a href="{{ url_for("words.index") }}">{{ gettext('Words') }}</a>
	  </li>
	  <li>
	    <a href="{{ url_for("words.add") }}">{{ gettext('Add') }}</a>
	  </li>
	  <li>
	    <a href="{{ url_for("words.search") }}">{{ gettext('Search') }}</a>
	  </li>
	</ul>
      </div>
      <div id="search" class="span-5 last">
	<div class="right">
	  {% include "_global_search.html" %}
	</div>
      </div>

      {% from "_common.html" import render_language_form with context %}

      <div id="language" class="span-5 last">
	<div class="right">
          {{ render_language_form("app_language") }}
	</div>
      </div>
    </div>
    
    {% macro with_errors(field) %}
      <div class="field">
	<label>{{ field.label }}</label>
	{% set css_class = kwargs.pop('class', '') %}
	{% if not css_class %}
	  {% set css_class = 'clearfix span-17 ' + css_class %}
	{% else %}
	  {% set css_class = 'clearfix ' + css_class %}
	{% endif %}
	{% if field.errors %}
	  
	  <div  class="clearfix">
	    {{ field(class=css_class, **kwargs) }}
	  </div>
	  <div class="notice">{% for error in field.errors %}<div>{{ error|e }}</div>{% endfor %}</div>
	{% else %}
	  <div class="clearfix">
	    {{ field(class=css_class, **kwargs) }}
	  </div>
        {% endif %}
      </div>
    {% endmacro %}

    <div id="main" class="clearfix">      
      {% with messages = get_flashed_messages(with_categories=true) %}
	{% if messages %}
	  <div id="flashes">
	    {% for category, message in messages %}
	      <div class="{{ category }}">{{ message }}</div>
	    {% endfor %}
	  </div>
	{% endif %}
      {% endwith %}
      
    </div>
    </div>
    <br />
    <hr />
    <div class="container clear">
      <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">
        <img alt="Creative Commons License" style="border-width:0"
             src="/static/img/cc-by-sa-88x31.png" /></a>
             <br />
             This <span xmlns:dct="http://purl.org/dc/terms/"
             href="http://purl.org/dc/dcmitype/Text"
             rel="dct:type">work</span> is licensed under a <a rel="license"
             href="http://creativecommons.org/licenses/by-sa/3.0/">Creative
             Commons Attribution-ShareAlike 3.0 Unported License</a>.
    </div>

    #}
    <script src="{{ url_for('static', filename='js/vendor/jquery-1.7.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/jquery.easing.1.3.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/jquery.placeholder.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/underscore-min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/backbone-min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/default.js') }}"></script>
  </body>
</html>