humusha/apps/words/forms.py
from sqlalchemy import or_

from flask_babel import gettext, ngettext, lazy_gettext as _
from flask import session

from flask_wtf import Form
from wtforms.fields import TextField, SubmitField, SelectField, HiddenField, FieldList, IntegerField
from wtforms.validators import Required as BaseRequired, ValidationError

from .models import Word, Part, WordPart, Relation, WordRelation, Language,\
    Translation


class Required(BaseRequired):
    def __init__(self, message=None):
        if message is None:
            message = _(u'This field is required.')
        super(Required, self).__init__(message)
        

class UniqueWord(object):
    """This class checks if the word does not exists."""
    def __init__(self, message=None):
        if not message:
            message = _(u'This word has already been added.')
        self.message = message

    def __call__(self, form, field):
        if Word.query.filter_by(word=field.data).count():
            raise ValidationError(self.message)

class RelationPart(object):
    """This class checks if the specified part can be a word relation."""
    def __init__(self, message=None):
        if not message:
            message = _(
                u'This part of speech can not be a relation.')
        self.message = message

    def __call__(self, form, field):
        try:
            part_id = int(field.data)
        except TypeError:
            part_id = None
            
        if not Relation.query.filter_by(part_id=part_id).count():
            raise ValidationError(self.message)


class TranslationLanguage(object):
    def __init__(self, message=None):
        if not message:
            message = _(
                u'This language has been added to this word part of speech.')
        self.message = message

    def __call__(self, form, field):
        try:
            part_id = int(form.part_id.data)
        except ValueError:
            part_id = None
        try:
            word_id = int(form.word_id.data)
        except ValueError:
            word_id = None
        if Translation.query.filter_by(part_id=part_id)\
                .filter_by(word_id=word_id).filter_by(language_id=int(field.data)).count():
            raise ValidationError(self.message)
    


class RelationLimit(object):
    """This class checks if added word relations have not reached the limit."""
    def __init__(self, message=None):
        if not message:
            message = _(
                u'The maximum word relations have been reached for this '\
                    'word and part of speech.')
        self.message = message

    def __call__(self, form, field):
        try:
            part_id = int(form.part.data)
        except TypeError:
            part_id = None
            
        relation = Relation.query.filter_by(part_id=part_id).first()
        if relation is None:
            raise ValidationError(self.message)

        word_count = WordRelation.query.filter(or_(
            WordRelation.word_id_1==form.word_id_,
            WordRelation.word_id_2==form.word_id_)).\
            filter(WordRelation.relation_id==relation.id).count()
        
        if word_count >= relation.limit and relation.limit:
            raise ValidationError(self.message)


class DynamicSelectField(SelectField):
    def __call__(self, parent_id=None, language_id=None, **kwargs):
        self.generate_choices(parent_id, language_id)

        return super(DynamicSelectField, self).__call__(**kwargs);

    def generate_choices(self, parent_id=None, language_id=None):
        parts = Part.query.filter_by(parent_id=parent_id)
        if language_id is not None:
            parts = parts.filter_by(language_id=language_id)
        if parent_id is None:
            parts = parts.filter(Part.name!='other')
        choices = [(p.id, _(p.label)) for p in parts]

        self.choices = choices
        
    

class SpeechTypeUnique(object):
    """This class checks if the word has been not been assigned to selected 
    type of speech.
    
    """
    def __init__(self, message=None):
        if not message:
            message = _(
                u'The selected type of speech is already associated with this word.'
            )
        self.message = message

    def __call__(self, form, field):
        if WordPart.query.filter_by(part_id=field.data,
                                    word_id=form.word_id_).count():
            raise ValidationError(self.message)


class WordForm(Form):
    word = TextField(_(_(u'Word')), validators=[
            Required(), UniqueWord()])
    language_id = HiddenField(_(u'Language'))
    submit = SubmitField(_(_(u'Add')))


class WordRelationForm(Form):
    word = FieldList(TextField(_(u'Word'), validators=[
                Required(), RelationLimit()]))
    word_relation = FieldList(HiddenField(_(u'Relation'), validators=[]))
    part = HiddenField(u'Part', validators=[RelationPart()])
    definition_id = HiddenField(_(u'Definition ID'), validators=[])
    translation_id = HiddenField(_(u'Translation ID'), validators=[])

    submit = SubmitField(_(u'Add'))
    
    @property
    def word_id(self):
        return self.word_id_

    @word_id.setter
    def word_id(self, value):
        self.word_id_ = value


class DefinitionForm(Form):
    definition = TextField(_(u'Definition'), validators=[])
    
    part = HiddenField(_(u'Part'), validators=[])
    definition_id = HiddenField(_(u'Definition ID'), validators=[])
    translation_id = HiddenField(_(u'Translation ID'), validators=[])

    submit = SubmitField(_(u'Define'))

class UsageForm(Form):
    sentence = FieldList(TextField(_(u'Usage examples'), []), min_entries=0)
    # sentence = FieldList(TextField(u'Usage examples', validators=[]))
    sentence_id = FieldList(HiddenField(_(u'Usage ID'), validators=[]))
    submit = SubmitField(_(u'Add'))


class SearchForm(Form):
    word = TextField(_(u'Word'), validators=[Required()])
    submit = SubmitField(_(u'Search'))


class TranslationForm(Form):
    language_id = SelectField(_(u'Language'), coerce=int, choices=[],
                              validators=[TranslationLanguage()])
    word_id = HiddenField(_(u'Word'))
    part_id = HiddenField(u'Part')
    submit = SubmitField(_(u'Add'))
    
    def language_choices(self):
        self.language_id.choices = [(l.id, l.label) for l in Language.query.all()]

class SpeechPartForm(Form):
    part = DynamicSelectField(_(u'Part of speech'), choices=[], coerce=int, validators=[
            SpeechTypeUnique()])

    parent_id = HiddenField(_(u'Parent type'))
    language_id = HiddenField(_(u'Language'))
    
    submit = SubmitField(_(u'Add'))

    @property
    def word_id(self):
        return self.word_id_
    
    @word_id.setter
    def word_id(self, value):
        self.word_id_ = value

    def validate(self):
        try:
            parent_id = int(self.parent_id.data)
            if not parent_id:
                parent_id = None
        except ValueError:
            parent_id = None
        try:
            language_id = int(self.language_id.data)
            if not language_id:
                language_id = None
        except ValueError:
            language_id = None

        parts = Part.query.filter_by(parent_id=parent_id)
        if language_id is None:
            parts = parts.filter_by(language_id=language_id)
        choices = [(p.id, p.label) for p in parts]
        self.part.choices = choices

        return super(SpeechPartForm, self).validate();

humusha/apps/words/views.py
from flask import render_template, flash, request, redirect, url_for, abort,\
    session, Blueprint
from werkzeug.datastructures import MultiDict
from flask_babel import gettext, ngettext, lazy_gettext as _

from humusha.utils.pagination import Pagination
from humusha import db

from .forms import WordForm, SearchForm, SpeechPartForm, DefinitionForm, \
    UsageForm, WordRelationForm, TranslationForm
from .models import Word, WordPart, Definition, Usage, Part, Relation,\
    WordRelation, Translation, Language, Change


words = Blueprint('words', __name__)

PER_PAGE = 80

@words.route('/')
@words.route('/<language_code>/', methods=['GET', 'POST'])
def index(language_code=None):
    page = request.args.get('page', 1)
    try:
        page = int(page)
        if page < 1:
            page = 1
    except ValueError:
        page = 1
    
    words = Word.query.order_by('word.id DESC')\
        .slice((page - 1)*PER_PAGE, page*PER_PAGE).all()

    words_count = Word.query.order_by('word.id DESC').count()
    pagination = Pagination(page, PER_PAGE, words_count)

    ctx = {
        'words': words,
        'pagination': pagination,
    }
    return render_template('words/words.html', **ctx)

@words.route('/browse/<starts_with>/')
@words.route('/browse/<starts_with>/<language_code>/', methods=['GET', 'POST'])
def browse(starts_with, language_code=None):
    page = request.args.get('page', 1)
    try:
        page = int(page)
        if page < 1:
            page = 1
    except ValueError:
        page = 1

    words = Word.query.filter(Word.word.startswith(starts_with))\
        .order_by('word.id DESC').slice((page - 1)*PER_PAGE, page*PER_PAGE).all()
    words_count = Word.query.filter(Word.word.startswith(starts_with)).count()
    pagination = Pagination(page, PER_PAGE, words_count)
        
    ctx = {
        'words': words,
        'pagination': pagination,
    }
    return render_template('words/browse.html', **ctx)


@words.route('/<word_data>', methods=['GET', 'POST'])
@words.route('/<language_code>/<word_data>', methods=['GET', 'POST'])
def view(word_data, language_code=None):
    word = Word.get_word(word_data, language_code)
    if word is None:
        abort(404)
    speech_parts = WordPart.query.join('part').filter(WordPart.word_id==word.id)\
        .filter(Part.parent_id==None)
    
    words = Word.query.filter(Word.word.like('%{0}%'.format(word_data)))
    thesaurus_parts = Part.thesaurus_parts(word.language_id)
    translation_part = Part.translation_part(word.language_id)

    ctx = {
        'word': word,
        'speech_parts': speech_parts,
        'words': words,
        'thesaurus_parts': thesaurus_parts,
        'translation_part': translation_part,
    }
    return render_template('words/view_word.html', **ctx)


@words.route('/<language_code>/edit/<word_data>/', methods=['GET', 'POST'])
@words.route('/<language_code>/edit/<word_data>/p<int:part_data>', methods=['GET', 'POST'])
@words.route('/<language_code>/edit/<word_data>/d<int:definition_data>', methods=['GET', 'POST'])
def edit(word_data, definition_data=None, part_data=None, language_code=None):
    word = Word.get_word(word_data, language_code)
    if word is None:
        abort(404)

    speech_parts = WordPart.query.join('part').filter(WordPart.word_id==word.id)\
        .filter(Part.parent_id == None)
    thesaurus_parts = Part.thesaurus_parts(word.language_id)

    translation_part = Part.translation_part(word.language_id)

    speech_part_form = SpeechPartForm()

    speech_part_form.word_id = word.id
    # speech_part_form.set_word(word.id)

    definition_form = DefinitionForm()
    usage_form = UsageForm()
    word_relation_form = WordRelationForm()
    translation_form = TranslationForm()
    translation_form.language_choices()

    words = Word.query.filter(Word.word.like('%{0}%'.format(word_data)))

    if speech_part_form.validate_on_submit():
        word_part = WordPart(word.id, speech_part_form.part.data)
        db.session.add(word_part)
        db.session.commit()
        flash(gettext(u'The word has been associated with the part of speech.'), 'success')
        
    ctx = {
        'word': word,
        'speech_parts': speech_parts,
        'usage_form': usage_form,
        'thesaurus_parts': thesaurus_parts,
        'translation_part': translation_part,
        'words': words,
        'word_relation_form': word_relation_form,
        'definition_form': definition_form,
        'speech_part_form': speech_part_form,
        'translation_form': translation_form,
    }
    return render_template('words/edit_word.html', **ctx)


@words.route('/<language_code>/add_definition/<word_data>', methods=['POST'])
def add_definition(word_data, language_code=None):
    word = Word.get_word(word_data, language_code)
    if word is None:
        abort(404)
    definition_form = DefinitionForm(csrf_enabled=False)
    usage_form = UsageForm(csrf_enabled=False)

    if definition_form.validate_on_submit() and usage_form.validate_on_submit():
        definition_data = definition_form.definition.data
        definition_id_data = definition_form.definition_id.data
        part_id_data = definition_form.part.data
        sentences_data = usage_form.sentence.data
        sentences_id_data = usage_form.sentence_id.data
        try:
            translation_id_data = int(definition_form.translation_id.data)
        except ValueError:
            translation_id_data = None

        part = Part.query.filter_by(id=part_id_data).first()
    
        try:
            definition_id_data = int(definition_id_data)
            definition = Definition.query.filter_by(id=definition_id_data).first()
        except ValueError:
            definition = None

        if definition_data and word is not None:
            if definition is not None:
                definition.definition=definition_data
            else:
                definition = Definition(
                    definition=definition_data,
                    word_id=word.id,
                    part_id=part_id_data)
                definition.translation_id = translation_id_data
            db.session.add(definition)
            db.session.commit()
            for sentence_index, sentence_data in enumerate(sentences_data):
                
                if not sentence_index > len(sentences_id_data)-1:
                    usage = Usage.query.filter_by(
                        id=sentences_id_data[sentence_index]).first()
                else:
                    usage = None
                if usage is not None:
                    if not sentence_data:
                        db.session.delete(usage)
                    else:
                        usage.sentence=sentence_data
                        db.session.add(usage)
                else:
                    if not sentence_data:
                        continue
                    usage = Usage(sentence=sentence_data,
                                  definition_id=definition.id)
                    db.session.add(usage)
            db.session.commit()
            flash(gettext(u'Definition added.'), 'success')
        else:
            flash(gettext(u'Definition not added.'), 'error')
    else:
        flash(gettext(u'Definition not added.'), 'error')

    return redirect(url_for('words.edit', language_code=language_code, word_data=word_data))


@words.route('/<language_code>/edit/relation/<word_data>', methods=['POST'])
def relation(word_data, language_code=None, form_class = WordRelationForm):
    word_relation_form = form_class()
    
    word_1 = Word.get_word(word_data, language_code)
    if word_1 is None:
        return redirect(url_for('words.edit', language_code=language_code, word_data=word_data))

    word_relation_form.word_id = word_1.id

    validates = word_relation_form.validate_on_submit()
    
    word_relation = None
    for word_index, word_data_2 in enumerate(word_relation_form.word.data):
        word_relation = None
        try:
            part_data = int(word_relation_form.part.data)
        except ValueError:
            part_data = None
        relation = Relation.query.filter(Relation.part_id==part_data).first()
        try:
            translation_id_data = int(word_relation_form.translation_id.data)
            translation = Translation.query\
                .filter(Translation.id==translation_id_data).first()
            language_id = translation.language_id
        except ValueError:
            translation_id_data = None
            translation = None
            language_id = word_1.language_id
        try:
            definition_id_data = int(word_relation_form.definition_id.data)
        except ValueError:
            definition_id_data = None

        if word_index < len(word_relation_form.word_relation.data): # Update
            word_relation_data = int(word_relation_form.word_relation.data[word_index])
        elif not validates: # Relation limit reached
            continue
        else: # New word relation
            word_relation_data = None

        word_2 = Word.query.filter(Word.word==word_data_2)\
            .filter(Word.language_id==language_id).first()

        if word_2 is None:
            word_2 = Word(word=word_data_2, language_id=language_id)
            db.session.add(word_2)
            db.session.commit()
            flash(gettext(u'Relation word was added.'), 'success')
        
        if word_relation_data is not None:
             word_relation = WordRelation.query\
                .filter(WordRelation.translation_id==translation_id_data)\
                .filter(WordRelation.relation_id==relation.id)\
                .filter(WordRelation.id==word_relation_data).first()
             if word_relation is None:
                 continue
        else:
            word_relation = WordRelation.query\
                .filter(WordRelation.translation_id==translation_id_data)\
                .filter(WordRelation.word_id_1==word_1.id)\

humusha/templates/words/edit/_definitions.html
{# START DEFINITIONS #}
<div class="row">
  {% for definition in word_part.word.definitions(word_part.part_id) %}
    {# START SINGLE DEFINITION #}
    <div class="large-11 columns">
      {% if not request.view_args.definition_data == definition.id %}
        <ul>
	  {# START DISPLAY DEFINITION #}
          <li>
            {{ definition.definition }}
            {#	      <div class="right">
	    <a href="{{ url_for("edit_word", word_data=word.word, definition_data=definition.id) }}">edit</a>
	    </div>   
            #}
          </li>
          <ol>
            {% for usage_example in definition.usage_examples %}
	      <li>
                <em>{{ usage_example.sentence }}</em>
              </li>
	    {% endfor %}
          </ol>
          {# END DISPLAY DEFINITION #}
        </ul>
      {% else %}
        {# START EDIT DEFINITION #}
        <div class="row">
          <form action="{{ url_for("words.add_definition", language_code=word.language.code, word_data=word.word) }}" name="definition" method="POST">
            {{ definition_form.part(value=word_part.part_id) }}
            <div class="large-6 columns">
              <label>{{ definition_form.definition.label }}</label>
              {{ definition_form.definition_id(value=definition.id) }}
              {{ definition_form.definition(value=definition.definition, class="span11") }}
            </div>
            <div class="large-6 columns">
              {# START EDIT USAGE EXAMPLE/SENTENCE #}
              <label>{{ usage_form.sentence.label }}</label>
              {% for usage_example in definition.usage_examples %}
		{{ usage_form.sentence.append_entry(usage_example.sentence) }}
                {{ usage_form.sentence_id.append_entry(usage_example.id) }}
	      {% endfor %}
              {{ usage_form.sentence.append_entry() }}
              <div class=" large-2">
                {{ definition_form.submit(value="Update", class="button postfix") }}
              </div>
              {# END EDIT USAGE EXAMPLE/SENTENCE #}
            </div>
          </form>
        </div>
        {# END EDIT DEFINITION #}
      {% endif %}
    </div>
    <div class="large-1 columns text-right">
      <a href="{{ url_for("words.edit", language_code=word.language.code, word_data=word.word, definition_data=definition.id) }}">edit</a>
    </div>
    {# END SINGLE DEFINITION #}
  {% endfor %}
</div>
{# END DEFINITIONS #}

{# START ADD DEFINITION #}
<div class="{% if request.view_args.definition_data %}hide{% else %}row{% endif %}">
  <form action="{{ url_for("words.add_definition", language_code=word.language.code, word_data=word.word) }}" name="definition" method="POST">
    {{ definition_form.part(value=word_part.part_id) }}
    <div class="large-6 columns">
      <label>{{ definition_form.definition.label }}</label>
      {{ definition_form.definition(class="span-10") }}
    </div>
    
    <div class="large-6 columns">
      
      <label>{{ usage_form.sentence.label }}</label>
      {{ usage_form.sentence.append_entry() }}
      {{ usage_form.sentence.append_entry() }}
      <div class=" large-2">
        {{ definition_form.submit(class="button postfix") }}
      </div>
    </div>
    
  </form>
</div>
{# END ADD DEFINITION #}

humusha/templates/words/edit/_master_part.html
<div class="row">
  <div class="large-3 columns">
    <h3>Type of word</h3>
  </div>
  <div class="large-4 columns">
    <form action="{{ url_for("words.edit", language_code=word.language.code, word_data=word.word) }}" method="POST">
      {{ speech_part_form.csrf_token }}
      {{ speech_part_form.parent_id(value=0) }}
      {{ speech_part_form.language_id(value=word.language_id) }}
      <div class="row collapse"> 
        <div class="large-10 columns"> 
          {{ speech_part_form.part(language_id=word.language_id) }}
        </div> 
        <div class="large-2 columns"> 
	  {{ speech_part_form.submit(class="button postfix") }}
        </div> 
      </div> 
      
      {% if speech_part_form.errors and speech_part_form.parent_id.data|int == 0 %} 
        <div class="control-group error"> 
          {% for field_errors in speech_part_form.errors if field_errors %} 
	    <span class="help-inline">{{ speech_part_form.errors[field_errors][0] }}</span><br /> 
	  {% endfor %} 
        </div> 
      {% endif %} 
    </form>
  </div>
  <div class="large-5 columns">
  </div>
</div>

humusha/templates/words/edit/_part_subpart.html
<div class="row">
  {% for part_type in word_part.part_types %}
    <div class="large-2 columns">
      <h5>{{ part_type.part.label }}</h5>
    </div>
    {% if part_type.part.relation.part_id %}
      <div class="large-1 columns">
        <em>{{ ngettext("of word", "of words", part_type.part.relation.limit) }}</em>
      </div>
      <div class="{% if part_type.part.relation.limit_reached(word.id) and not request.view_args.part_data == part_type.part.id %}hide{% else %}large-5 columns{% endif %}">
        <form action="{{ url_for("words.relation", language_code=word.language.code, word_data=word.word) }}" method="POST">
          {{ word_relation_form.csrf_token }}
          <div class="large-9 columns">
            <div class="hide relation-limit">{{ part_type.part.relation.limit }}</div>
            {% if request.view_args.part_data == part_type.part.id %}
              {# Edit type of speech related words #}
              
              {% for word_relation in word.relations(part_type.part.id) %}
                {{ word_relation_form.word_relation.append_entry(word_relation.id) }}
                {% if not word_relation.word_id_1 == word.id %}
                  {{ word_relation_form.word.append_entry(word_relation.word_1.word) }}
                {% else %}
                  {{ word_relation_form.word.append_entry(word_relation.word_2.word) }}
                {% endif %}
              {% endfor %}
              {# 0 for unrestricted word relations #}
              {% if not part_type.part.relation.limit or loop.index < part_type.part.relation.limit %}
                {{ word_relation_form.word.append_entry() }}
              {% endif %}
            {% else %}
              {{ word_relation_form.word.append_entry() }}
            {% endif %}
            {{ word_relation_form.part(value=part_type.part.id) }}
                                                                      </div>
          <div class=" large-3 columns">
            {{ word_relation_form.submit(class="button postfix") }}
          </div>
        </form>
      </div>

      {% if word.relations(part_type.part.id).count() and not request.view_args.part_data == part_type.part.id %}
        <div class="large-8 columns">
          {# Type of speech related words #}
          {% for word_relation in word.relations(part_type.part.id) %}
            <div class="large-2 columns">                  
              {% if not word_relation.word_id_1 == word.id %}
                {{ word_relation.word_1.word }}
              {% else %}
                {{ word_relation.word_2.word }}
              {% endif %}
            </div>
          {% endfor %}
        </div>
      {% endif %}
      
      <div class="large-1 columns text-right">
        <a href="{{ url_for("words.edit", language_code=word.language.code, word_data=word.word, part_data=part_type.part.id) }}">edit</a>
      </div>

{% endif %}
{% endfor %}
</div>

humusha/templates/words/edit/_thesaurus.html
{% for thesaurus_part in thesaurus_parts %}
  <div class="row _parts">
    <div class="large-12 columns _header">
      <h4>{{ thesaurus_part.label }}</h4>
    </div>
    
    <div class="_content">

      <div class="large-12 columns">
        <div class="row">
          <div class="large-3 columns">
            <h6>Ungrouped Translations</h6>
          </div>

          <div class="large-4 columns">
            {# START ADD WORD WITHOUT CONTEXT #}
            <form action="{{ url_for("words.relation", language_code=word.language.code, word_data=word.word) }}" method="POST">
              {{ word_relation_form.csrf_token }}
              {{ word_relation_form.part(value=thesaurus_part.id) }}
              <div class="row collapse"> 
                <div class="large-8 columns">
                  {{ word_relation_form.word.append_entry() }}
                </div>
                <div class="large-4 columns">

                  {{ word_relation_form.submit(class="button postfix") }}
                </div>
              </div>
            </form>
            {# END ADD WORD WITHOUT CONTEXT #}
          </div>
          <div class="large-5 columns">&nbsp;</div>
        </div>
        <ul>
          {# START THESAURUS WORDS WITHOUT CONTEXT #}
          {% for word_relation in word.relations(thesaurus_part.id) %}
            <li>
              {% if not word_relation.word_id_1 == word.id %}
                {{ word_relation.word_1.word }}
              {% else %}
                {{ word_relation.word_2.word }}
              {% endif %}
            </li>
          {% endfor %}
          {# START THESAURUS WORDS WITHOUT CONTEXT #}
        </ul>
      </div>





      <div class="_content">
        {# START THESAURUS CONTEXT #}
        <div class="large-12 columns">
          
          <div class="row">
            <div class="large-3 columns">
              <h6>Grouped Translations</h6>
            </div>
            <div class="large-6 columns">
              {# START ADD THESAURUS CONTEXT #}
              <form action="{{ url_for("words.add_definition", language_code=word.language.code, word_data=word.word) }}" name="definition" method="POST">
                {{ definition_form.part(value=thesaurus_part.id) }}
                <div class="row collapse"> 
                  <div class="large-10 columns">
                    {{ definition_form.definition() }}
                  </div>
                  <div class="large-2 columns">
                    {{ definition_form.submit(class="button postfix") }}
                  </div>
                </div>
              </form>
              {# END ADD THESAURUS CONTEXT #}
            </div>
            <div class="large-3 columns">&nbsp;</div>
          </div>





          <ol>
            {% for definition in word.definitions(thesaurus_part.id) %}
              <div class="row">
                <div class="large-8 columns">
                  
                  {% if not request.view_args.definition_data == definition.id %}
	            <li>
	              {{ definition.definition }}
                      &nbsp;&nbsp; - &nbsp;
                      <a href="{{ url_for("words.edit", language_code=word.language.code, word_data=word.word, definition_data=definition.id) }}">edit</a>
                    </li>
                  {% else %}
	            <div class="row">
                      <form action="{{ url_for("words.add_definition", language_code=word.language.code, word_data=word.word) }}" name="definition" method="POST">
                        {{ definition_form.definition_id(value=definition.id) }}
                        {{ definition_form.part(value=thesaurus_part.id) }}
                        <div class="row collapse"> 
                          <div class="large-10 columns">
                            {{ definition_form.definition(value=definition.definition) }}
                          </div>
                          <div class="large-2 columns">
                            {{ definition_form.submit(value="Update", class="button postfix") }}
                          </div>
                        </div>
                      </form>
                    </div>
                  {% endif %}

                  <div class="row">
                    {# START DISPLAY CONTEXT WORDS #}
                    <ul>
                      {% for word_relation in word.relations(thesaurus_part.id, definition.id) %}
                        <li>
                          {% if not word_relation.word_id_1 == word.id %}
                            {{ word_relation.word_1.word }}
                          {% else %}
                            {{ word_relation.word_2.word }}
                          {% endif %}
                        </li>
                      {% endfor %}
                    </ul>
                    {# END DISPLAY CONTEXT WORDS #}
                  </div>
                  

                  
                </div>
                <div class="large-1 columns">
                  &nbsp;
                </div>
                <div class="large-3 columns">
                  <div class="row">
                    {# START EDIT CONTEXT WORDS #}
                    <form action="{{ url_for("words.relation", language_code=word.language.code, word_data=word.word) }}" method="POST">
                      {{ word_relation_form.csrf_token }}
                      {{ word_relation_form.part(value=thesaurus_part.id) }}
                      {{ definition_form.definition_id(value=definition.id) }}
                      <div class="row collapse"> 
                        <div class="large-8 columns">
                          
                          {{ word_relation_form.word.append_entry() }}
                        </div>
                        <div class="large-4 columns">
                          
                          {{ word_relation_form.submit(class="button postfix") }}
                        </div>
                      </div>
                    </form>
                    {# END EDIT CONTEXT WORDS #}
                  </div>
                  
                </div>

              </div>
              {# END THESAURUS CONTEXT #}
            {% endfor %}
          </ol>

        </div>
        {# END THESAURUS CONTEXT #}
      </div>



    </div>
  </div>
{% endfor %}